/// On-device vocabulary database mapping ML Kit image labels to CEFR vocabulary.
///
/// Contains 120+ entries organized by category, each with English word,
/// Thai translation, CEFR level, IPA phonetic, example sentence, and category.
/// All data is built-in (no network required) for standalone APK deployment.
library;

class ScannedVocabulary {
  final String mlLabel;
  final String englishWord;
  final String thaiTranslation;
  final String cefrLevel;
  final String phonetic;
  final String exampleSentence;
  final String category;

  const ScannedVocabulary({
    required this.mlLabel,
    required this.englishWord,
    required this.thaiTranslation,
    required this.cefrLevel,
    required this.phonetic,
    required this.exampleSentence,
    required this.category,
  });
}

class ObjectVocabularyDatabase {
  const ObjectVocabularyDatabase();

  /// Look up vocabulary by ML Kit label (case-insensitive).
  ScannedVocabulary? lookupByMlLabel(String label) {
    final key = label.toLowerCase().trim();
    for (final entry in _entries) {
      if (entry.mlLabel.toLowerCase() == key) return entry;
    }
    // Partial match fallback: check if the label contains an entry keyword.
    for (final entry in _entries) {
      if (key.contains(entry.mlLabel.toLowerCase()) ||
          entry.mlLabel.toLowerCase().contains(key)) {
        return entry;
      }
    }
    return null;
  }

  /// Get all entries in a specific category.
  List<ScannedVocabulary> getByCategory(String category) {
    return _entries
        .where((e) => e.category.toLowerCase() == category.toLowerCase())
        .toList();
  }

  /// Get all entries at a specific CEFR level.
  List<ScannedVocabulary> getByCefrLevel(String level) {
    return _entries
        .where((e) => e.cefrLevel.toUpperCase() == level.toUpperCase())
        .toList();
  }

  /// Get all available categories.
  List<String> get categories =>
      _entries.map((e) => e.category).toSet().toList()..sort();

  /// Total number of entries.
  int get totalEntries => _entries.length;

  /// All entries.
  List<ScannedVocabulary> get allEntries => List.unmodifiable(_entries);

  // ─────────────────────────────────────────────────────────────────
  //  Built-in vocabulary database (120+ entries, 10 categories)
  // ─────────────────────────────────────────────────────────────────

  static const List<ScannedVocabulary> _entries = [
    // ── Food & Drinks (อาหารและเครื่องดื่ม) ──
    ScannedVocabulary(
      mlLabel: 'Apple',
      englishWord: 'apple',
      thaiTranslation: 'แอปเปิ้ล',
      cefrLevel: 'A1',
      phonetic: '/ˈæp.əl/',
      exampleSentence: 'I eat an apple every morning.',
      category: 'Food & Drinks',
    ),
    ScannedVocabulary(
      mlLabel: 'Banana',
      englishWord: 'banana',
      thaiTranslation: 'กล้วย',
      cefrLevel: 'A1',
      phonetic: '/bəˈnɑː.nə/',
      exampleSentence: 'Bananas are rich in potassium.',
      category: 'Food & Drinks',
    ),
    ScannedVocabulary(
      mlLabel: 'Orange',
      englishWord: 'orange',
      thaiTranslation: 'ส้ม',
      cefrLevel: 'A1',
      phonetic: '/ˈɒr.ɪndʒ/',
      exampleSentence: 'Would you like some orange juice?',
      category: 'Food & Drinks',
    ),
    ScannedVocabulary(
      mlLabel: 'Bread',
      englishWord: 'bread',
      thaiTranslation: 'ขนมปัง',
      cefrLevel: 'A1',
      phonetic: '/bred/',
      exampleSentence: 'I had toast and bread for breakfast.',
      category: 'Food & Drinks',
    ),
    ScannedVocabulary(
      mlLabel: 'Cake',
      englishWord: 'cake',
      thaiTranslation: 'เค้ก',
      cefrLevel: 'A1',
      phonetic: '/keɪk/',
      exampleSentence: 'She baked a chocolate cake.',
      category: 'Food & Drinks',
    ),
    ScannedVocabulary(
      mlLabel: 'Coffee',
      englishWord: 'coffee',
      thaiTranslation: 'กาแฟ',
      cefrLevel: 'A1',
      phonetic: '/ˈkɒf.i/',
      exampleSentence: 'I drink coffee every morning.',
      category: 'Food & Drinks',
    ),
    ScannedVocabulary(
      mlLabel: 'Tea',
      englishWord: 'tea',
      thaiTranslation: 'ชา',
      cefrLevel: 'A1',
      phonetic: '/tiː/',
      exampleSentence: 'Would you like a cup of tea?',
      category: 'Food & Drinks',
    ),
    ScannedVocabulary(
      mlLabel: 'Water bottle',
      englishWord: 'water bottle',
      thaiTranslation: 'ขวดน้ำ',
      cefrLevel: 'A1',
      phonetic: '/ˈwɔː.tər ˌbɒt.əl/',
      exampleSentence: 'Please bring your water bottle.',
      category: 'Food & Drinks',
    ),
    ScannedVocabulary(
      mlLabel: 'Pizza',
      englishWord: 'pizza',
      thaiTranslation: 'พิซซ่า',
      cefrLevel: 'A1',
      phonetic: '/ˈpiːt.sə/',
      exampleSentence: 'Let us order a pizza for dinner.',
      category: 'Food & Drinks',
    ),
    ScannedVocabulary(
      mlLabel: 'Ice cream',
      englishWord: 'ice cream',
      thaiTranslation: 'ไอศกรีม',
      cefrLevel: 'A1',
      phonetic: '/ˌaɪs ˈkriːm/',
      exampleSentence: 'Children love eating ice cream.',
      category: 'Food & Drinks',
    ),
    ScannedVocabulary(
      mlLabel: 'Egg',
      englishWord: 'egg',
      thaiTranslation: 'ไข่',
      cefrLevel: 'A1',
      phonetic: '/eɡ/',
      exampleSentence: 'I had a boiled egg for breakfast.',
      category: 'Food & Drinks',
    ),
    ScannedVocabulary(
      mlLabel: 'Rice',
      englishWord: 'rice',
      thaiTranslation: 'ข้าว',
      cefrLevel: 'A1',
      phonetic: '/raɪs/',
      exampleSentence: 'Rice is the main food in Thailand.',
      category: 'Food & Drinks',
    ),

    // ── Technology (เทคโนโลยี) ──
    ScannedVocabulary(
      mlLabel: 'Laptop',
      englishWord: 'laptop',
      thaiTranslation: 'คอมพิวเตอร์พกพา',
      cefrLevel: 'A2',
      phonetic: '/ˈlæp.tɒp/',
      exampleSentence: 'I use my laptop for studying.',
      category: 'Technology',
    ),
    ScannedVocabulary(
      mlLabel: 'Mobile phone',
      englishWord: 'mobile phone',
      thaiTranslation: 'โทรศัพท์มือถือ',
      cefrLevel: 'A1',
      phonetic: '/ˌməʊ.baɪl ˈfəʊn/',
      exampleSentence: 'My mobile phone is on the table.',
      category: 'Technology',
    ),
    ScannedVocabulary(
      mlLabel: 'Tablet computer',
      englishWord: 'tablet',
      thaiTranslation: 'แท็บเล็ต',
      cefrLevel: 'A2',
      phonetic: '/ˈtæb.lɪt/',
      exampleSentence: 'She reads books on her tablet.',
      category: 'Technology',
    ),
    ScannedVocabulary(
      mlLabel: 'Keyboard',
      englishWord: 'keyboard',
      thaiTranslation: 'แป้นพิมพ์',
      cefrLevel: 'A2',
      phonetic: '/ˈkiː.bɔːd/',
      exampleSentence: 'This wireless keyboard is very comfortable.',
      category: 'Technology',
    ),
    ScannedVocabulary(
      mlLabel: 'Mouse',
      englishWord: 'mouse',
      thaiTranslation: 'เมาส์',
      cefrLevel: 'A2',
      phonetic: '/maʊs/',
      exampleSentence: 'Click the right mouse button.',
      category: 'Technology',
    ),
    ScannedVocabulary(
      mlLabel: 'Headphones',
      englishWord: 'headphones',
      thaiTranslation: 'หูฟัง',
      cefrLevel: 'B1',
      phonetic: '/ˈhed.fəʊnz/',
      exampleSentence: 'I listen to music with my headphones.',
      category: 'Technology',
    ),
    ScannedVocabulary(
      mlLabel: 'Television',
      englishWord: 'television',
      thaiTranslation: 'โทรทัศน์',
      cefrLevel: 'A1',
      phonetic: '/ˈtel.ɪ.vɪʒ.ən/',
      exampleSentence: 'We watch the news on television.',
      category: 'Technology',
    ),
    ScannedVocabulary(
      mlLabel: 'Camera',
      englishWord: 'camera',
      thaiTranslation: 'กล้องถ่ายรูป',
      cefrLevel: 'A2',
      phonetic: '/ˈkæm.rə/',
      exampleSentence: 'She took a photo with her camera.',
      category: 'Technology',
    ),
    ScannedVocabulary(
      mlLabel: 'Speaker',
      englishWord: 'speaker',
      thaiTranslation: 'ลำโพง',
      cefrLevel: 'B1',
      phonetic: '/ˈspiː.kər/',
      exampleSentence: 'Turn up the speaker volume.',
      category: 'Technology',
    ),
    ScannedVocabulary(
      mlLabel: 'Charger',
      englishWord: 'charger',
      thaiTranslation: 'ที่ชาร์จ',
      cefrLevel: 'A2',
      phonetic: '/ˈtʃɑːr.dʒər/',
      exampleSentence: 'I forgot my phone charger at home.',
      category: 'Technology',
    ),
    ScannedVocabulary(
      mlLabel: 'Monitor',
      englishWord: 'monitor',
      thaiTranslation: 'จอมอนิเตอร์',
      cefrLevel: 'B1',
      phonetic: '/ˈmɒn.ɪ.tər/',
      exampleSentence: 'The monitor displays a clear image.',
      category: 'Technology',
    ),
    ScannedVocabulary(
      mlLabel: 'Printer',
      englishWord: 'printer',
      thaiTranslation: 'เครื่องพิมพ์',
      cefrLevel: 'B1',
      phonetic: '/ˈprɪn.tər/',
      exampleSentence: 'The printer is out of ink.',
      category: 'Technology',
    ),

    // ── Clothing & Accessories (เสื้อผ้าและเครื่องแต่งกาย) ──
    ScannedVocabulary(
      mlLabel: 'Shirt',
      englishWord: 'shirt',
      thaiTranslation: 'เสื้อเชิ้ต',
      cefrLevel: 'A1',
      phonetic: '/ʃɜːt/',
      exampleSentence: 'He wore a white shirt to work.',
      category: 'Clothing',
    ),
    ScannedVocabulary(
      mlLabel: 'Shoe',
      englishWord: 'shoe',
      thaiTranslation: 'รองเท้า',
      cefrLevel: 'A1',
      phonetic: '/ʃuː/',
      exampleSentence: 'These shoes are very comfortable.',
      category: 'Clothing',
    ),
    ScannedVocabulary(
      mlLabel: 'Hat',
      englishWord: 'hat',
      thaiTranslation: 'หมวก',
      cefrLevel: 'A1',
      phonetic: '/hæt/',
      exampleSentence: 'She wore a straw hat at the beach.',
      category: 'Clothing',
    ),
    ScannedVocabulary(
      mlLabel: 'Sunglasses',
      englishWord: 'sunglasses',
      thaiTranslation: 'แว่นกันแดด',
      cefrLevel: 'A2',
      phonetic: '/ˈsʌnˌɡlɑː.sɪz/',
      exampleSentence: 'He put on his sunglasses outside.',
      category: 'Clothing',
    ),
    ScannedVocabulary(
      mlLabel: 'Watch',
      englishWord: 'watch',
      thaiTranslation: 'นาฬิกาข้อมือ',
      cefrLevel: 'A1',
      phonetic: '/wɒtʃ/',
      exampleSentence: 'My watch shows the wrong time.',
      category: 'Clothing',
    ),
    ScannedVocabulary(
      mlLabel: 'Backpack',
      englishWord: 'backpack',
      thaiTranslation: 'กระเป๋าเป้',
      cefrLevel: 'A2',
      phonetic: '/ˈbæk.pæk/',
      exampleSentence: 'I carry my books in a backpack.',
      category: 'Clothing',
    ),
    ScannedVocabulary(
      mlLabel: 'Jacket',
      englishWord: 'jacket',
      thaiTranslation: 'เสื้อแจ็คเก็ต',
      cefrLevel: 'A2',
      phonetic: '/ˈdʒæk.ɪt/',
      exampleSentence: 'Bring a jacket because it is cold tonight.',
      category: 'Clothing',
    ),
    ScannedVocabulary(
      mlLabel: 'Trousers',
      englishWord: 'trousers',
      thaiTranslation: 'กางเกงขายาว',
      cefrLevel: 'A2',
      phonetic: '/ˈtraʊ.zərz/',
      exampleSentence: 'He ironed his trousers for the meeting.',
      category: 'Clothing',
    ),
    ScannedVocabulary(
      mlLabel: 'Dress',
      englishWord: 'dress',
      thaiTranslation: 'ชุดกระโปรง',
      cefrLevel: 'A1',
      phonetic: '/dres/',
      exampleSentence: 'She bought a red dress for the party.',
      category: 'Clothing',
    ),
    ScannedVocabulary(
      mlLabel: 'Belt',
      englishWord: 'belt',
      thaiTranslation: 'เข็มขัด',
      cefrLevel: 'A2',
      phonetic: '/belt/',
      exampleSentence: 'He fastened his leather belt.',
      category: 'Clothing',
    ),
    ScannedVocabulary(
      mlLabel: 'Scarf',
      englishWord: 'scarf',
      thaiTranslation: 'ผ้าพันคอ',
      cefrLevel: 'B1',
      phonetic: '/skɑːf/',
      exampleSentence: 'She wrapped a scarf around her neck.',
      category: 'Clothing',
    ),
    ScannedVocabulary(
      mlLabel: 'Glove',
      englishWord: 'glove',
      thaiTranslation: 'ถุงมือ',
      cefrLevel: 'B1',
      phonetic: '/ɡlʌv/',
      exampleSentence: 'Wear gloves to keep your hands warm.',
      category: 'Clothing',
    ),

    // ── Animals (สัตว์) ──
    ScannedVocabulary(
      mlLabel: 'Dog',
      englishWord: 'dog',
      thaiTranslation: 'สุนัข',
      cefrLevel: 'A1',
      phonetic: '/dɒɡ/',
      exampleSentence: 'The dog is playing in the garden.',
      category: 'Animals',
    ),
    ScannedVocabulary(
      mlLabel: 'Cat',
      englishWord: 'cat',
      thaiTranslation: 'แมว',
      cefrLevel: 'A1',
      phonetic: '/kæt/',
      exampleSentence: 'The cat is sleeping on the sofa.',
      category: 'Animals',
    ),
    ScannedVocabulary(
      mlLabel: 'Bird',
      englishWord: 'bird',
      thaiTranslation: 'นก',
      cefrLevel: 'A1',
      phonetic: '/bɜːd/',
      exampleSentence: 'A bird is singing in the tree.',
      category: 'Animals',
    ),
    ScannedVocabulary(
      mlLabel: 'Fish',
      englishWord: 'fish',
      thaiTranslation: 'ปลา',
      cefrLevel: 'A1',
      phonetic: '/fɪʃ/',
      exampleSentence: 'There are many fish in the pond.',
      category: 'Animals',
    ),
    ScannedVocabulary(
      mlLabel: 'Butterfly',
      englishWord: 'butterfly',
      thaiTranslation: 'ผีเสื้อ',
      cefrLevel: 'A2',
      phonetic: '/ˈbʌt.ə.flaɪ/',
      exampleSentence: 'A beautiful butterfly landed on the flower.',
      category: 'Animals',
    ),
    ScannedVocabulary(
      mlLabel: 'Horse',
      englishWord: 'horse',
      thaiTranslation: 'ม้า',
      cefrLevel: 'A1',
      phonetic: '/hɔːs/',
      exampleSentence: 'She learned to ride a horse.',
      category: 'Animals',
    ),
    ScannedVocabulary(
      mlLabel: 'Elephant',
      englishWord: 'elephant',
      thaiTranslation: 'ช้าง',
      cefrLevel: 'A2',
      phonetic: '/ˈel.ɪ.fənt/',
      exampleSentence: 'The elephant is the national animal of Thailand.',
      category: 'Animals',
    ),
    ScannedVocabulary(
      mlLabel: 'Rabbit',
      englishWord: 'rabbit',
      thaiTranslation: 'กระต่าย',
      cefrLevel: 'A2',
      phonetic: '/ˈræb.ɪt/',
      exampleSentence: 'The rabbit hopped across the field.',
      category: 'Animals',
    ),
    ScannedVocabulary(
      mlLabel: 'Turtle',
      englishWord: 'turtle',
      thaiTranslation: 'เต่า',
      cefrLevel: 'A2',
      phonetic: '/ˈtɜː.təl/',
      exampleSentence: 'The turtle moves very slowly.',
      category: 'Animals',
    ),
    ScannedVocabulary(
      mlLabel: 'Frog',
      englishWord: 'frog',
      thaiTranslation: 'กบ',
      cefrLevel: 'A2',
      phonetic: '/frɒɡ/',
      exampleSentence: 'The frog jumped into the water.',
      category: 'Animals',
    ),
    ScannedVocabulary(
      mlLabel: 'Duck',
      englishWord: 'duck',
      thaiTranslation: 'เป็ด',
      cefrLevel: 'A1',
      phonetic: '/dʌk/',
      exampleSentence: 'The ducks are swimming in the lake.',
      category: 'Animals',
    ),
    ScannedVocabulary(
      mlLabel: 'Parrot',
      englishWord: 'parrot',
      thaiTranslation: 'นกแก้ว',
      cefrLevel: 'B1',
      phonetic: '/ˈpær.ət/',
      exampleSentence: 'The parrot can repeat what you say.',
      category: 'Animals',
    ),

    // ── Furniture (เฟอร์นิเจอร์) ──
    ScannedVocabulary(
      mlLabel: 'Chair',
      englishWord: 'chair',
      thaiTranslation: 'เก้าอี้',
      cefrLevel: 'A1',
      phonetic: '/tʃeər/',
      exampleSentence: 'Please sit on this chair.',
      category: 'Furniture',
    ),
    ScannedVocabulary(
      mlLabel: 'Table',
      englishWord: 'table',
      thaiTranslation: 'โต๊ะ',
      cefrLevel: 'A1',
      phonetic: '/ˈteɪ.bəl/',
      exampleSentence: 'Put your books on the table.',
      category: 'Furniture',
    ),
    ScannedVocabulary(
      mlLabel: 'Desk',
      englishWord: 'desk',
      thaiTranslation: 'โต๊ะทำงาน',
      cefrLevel: 'A1',
      phonetic: '/desk/',
      exampleSentence: 'The teacher stood behind the desk.',
      category: 'Furniture',
    ),
    ScannedVocabulary(
      mlLabel: 'Bed',
      englishWord: 'bed',
      thaiTranslation: 'เตียง',
      cefrLevel: 'A1',
      phonetic: '/bed/',
      exampleSentence: 'I go to bed at 10 PM.',
      category: 'Furniture',
    ),
    ScannedVocabulary(
      mlLabel: 'Couch',
      englishWord: 'couch',
      thaiTranslation: 'โซฟา',
      cefrLevel: 'A2',
      phonetic: '/kaʊtʃ/',
      exampleSentence: 'We sat on the couch and watched TV.',
      category: 'Furniture',
    ),
    ScannedVocabulary(
      mlLabel: 'Bookshelf',
      englishWord: 'bookshelf',
      thaiTranslation: 'ชั้นวางหนังสือ',
      cefrLevel: 'A2',
      phonetic: '/ˈbʊk.ʃelf/',
      exampleSentence: 'The bookshelf is full of novels.',
      category: 'Furniture',
    ),
    ScannedVocabulary(
      mlLabel: 'Lamp',
      englishWord: 'lamp',
      thaiTranslation: 'โคมไฟ',
      cefrLevel: 'A2',
      phonetic: '/læmp/',
      exampleSentence: 'Turn on the lamp, please.',
      category: 'Furniture',
    ),
    ScannedVocabulary(
      mlLabel: 'Mirror',
      englishWord: 'mirror',
      thaiTranslation: 'กระจก',
      cefrLevel: 'A2',
      phonetic: '/ˈmɪr.ər/',
      exampleSentence: 'She looked at herself in the mirror.',
      category: 'Furniture',
    ),
    ScannedVocabulary(
      mlLabel: 'Door',
      englishWord: 'door',
      thaiTranslation: 'ประตู',
      cefrLevel: 'A1',
      phonetic: '/dɔːr/',
      exampleSentence: 'Please close the door behind you.',
      category: 'Furniture',
    ),
    ScannedVocabulary(
      mlLabel: 'Window',
      englishWord: 'window',
      thaiTranslation: 'หน้าต่าง',
      cefrLevel: 'A1',
      phonetic: '/ˈwɪn.dəʊ/',
      exampleSentence: 'Open the window to let fresh air in.',
      category: 'Furniture',
    ),
    ScannedVocabulary(
      mlLabel: 'Pillow',
      englishWord: 'pillow',
      thaiTranslation: 'หมอน',
      cefrLevel: 'A2',
      phonetic: '/ˈpɪl.əʊ/',
      exampleSentence: 'This pillow is very soft.',
      category: 'Furniture',
    ),
    ScannedVocabulary(
      mlLabel: 'Curtain',
      englishWord: 'curtain',
      thaiTranslation: 'ม่าน',
      cefrLevel: 'B1',
      phonetic: '/ˈkɜː.tən/',
      exampleSentence: 'Close the curtains to block the sunlight.',
      category: 'Furniture',
    ),

    // ── Office Supplies (อุปกรณ์สำนักงาน) ──
    ScannedVocabulary(
      mlLabel: 'Book',
      englishWord: 'book',
      thaiTranslation: 'หนังสือ',
      cefrLevel: 'A1',
      phonetic: '/bʊk/',
      exampleSentence: 'I am reading an interesting book.',
      category: 'Office Supplies',
    ),
    ScannedVocabulary(
      mlLabel: 'Pen',
      englishWord: 'pen',
      thaiTranslation: 'ปากกา',
      cefrLevel: 'A1',
      phonetic: '/pen/',
      exampleSentence: 'Can I borrow your pen?',
      category: 'Office Supplies',
    ),
    ScannedVocabulary(
      mlLabel: 'Pencil',
      englishWord: 'pencil',
      thaiTranslation: 'ดินสอ',
      cefrLevel: 'A1',
      phonetic: '/ˈpen.səl/',
      exampleSentence: 'Write your answers in pencil.',
      category: 'Office Supplies',
    ),
    ScannedVocabulary(
      mlLabel: 'Scissors',
      englishWord: 'scissors',
      thaiTranslation: 'กรรไกร',
      cefrLevel: 'A2',
      phonetic: '/ˈsɪz.ərz/',
      exampleSentence: 'Use scissors to cut the paper.',
      category: 'Office Supplies',
    ),
    ScannedVocabulary(
      mlLabel: 'Paper',
      englishWord: 'paper',
      thaiTranslation: 'กระดาษ',
      cefrLevel: 'A1',
      phonetic: '/ˈpeɪ.pər/',
      exampleSentence: 'I need a piece of paper.',
      category: 'Office Supplies',
    ),
    ScannedVocabulary(
      mlLabel: 'Envelope',
      englishWord: 'envelope',
      thaiTranslation: 'ซองจดหมาย',
      cefrLevel: 'B1',
      phonetic: '/ˈen.və.ləʊp/',
      exampleSentence: 'Put the letter in the envelope.',
      category: 'Office Supplies',
    ),
    ScannedVocabulary(
      mlLabel: 'Ruler',
      englishWord: 'ruler',
      thaiTranslation: 'ไม้บรรทัด',
      cefrLevel: 'A2',
      phonetic: '/ˈruː.lər/',
      exampleSentence: 'Use a ruler to draw a straight line.',
      category: 'Office Supplies',
    ),
    ScannedVocabulary(
      mlLabel: 'Calculator',
      englishWord: 'calculator',
      thaiTranslation: 'เครื่องคิดเลข',
      cefrLevel: 'B1',
      phonetic: '/ˈkæl.kjə.leɪ.tər/',
      exampleSentence: 'You may use a calculator during the exam.',
      category: 'Office Supplies',
    ),
    ScannedVocabulary(
      mlLabel: 'Notebook',
      englishWord: 'notebook',
      thaiTranslation: 'สมุด',
      cefrLevel: 'A1',
      phonetic: '/ˈnəʊt.bʊk/',
      exampleSentence: 'Write down the new words in your notebook.',
      category: 'Office Supplies',
    ),
    ScannedVocabulary(
      mlLabel: 'Eraser',
      englishWord: 'eraser',
      thaiTranslation: 'ยางลบ',
      cefrLevel: 'A1',
      phonetic: '/ɪˈreɪ.zər/',
      exampleSentence: 'I need an eraser to correct my mistake.',
      category: 'Office Supplies',
    ),
    ScannedVocabulary(
      mlLabel: 'Stapler',
      englishWord: 'stapler',
      thaiTranslation: 'เครื่องเย็บกระดาษ',
      cefrLevel: 'B1',
      phonetic: '/ˈsteɪ.plər/',
      exampleSentence: 'Please staple these pages together.',
      category: 'Office Supplies',
    ),
    ScannedVocabulary(
      mlLabel: 'Folder',
      englishWord: 'folder',
      thaiTranslation: 'แฟ้มเอกสาร',
      cefrLevel: 'B1',
      phonetic: '/ˈfəʊl.dər/',
      exampleSentence: 'Keep your documents in a folder.',
      category: 'Office Supplies',
    ),

    // ── Vehicles (ยานพาหนะ) ──
    ScannedVocabulary(
      mlLabel: 'Car',
      englishWord: 'car',
      thaiTranslation: 'รถยนต์',
      cefrLevel: 'A1',
      phonetic: '/kɑːr/',
      exampleSentence: 'She drives a red car to work.',
      category: 'Vehicles',
    ),
    ScannedVocabulary(
      mlLabel: 'Bicycle',
      englishWord: 'bicycle',
      thaiTranslation: 'จักรยาน',
      cefrLevel: 'A1',
      phonetic: '/ˈbaɪ.sɪ.kəl/',
      exampleSentence: 'I ride my bicycle to school.',
      category: 'Vehicles',
    ),
    ScannedVocabulary(
      mlLabel: 'Bus',
      englishWord: 'bus',
      thaiTranslation: 'รถบัส',
      cefrLevel: 'A1',
      phonetic: '/bʌs/',
      exampleSentence: 'The bus arrives at 8 AM.',
      category: 'Vehicles',
    ),
    ScannedVocabulary(
      mlLabel: 'Motorcycle',
      englishWord: 'motorcycle',
      thaiTranslation: 'จักรยานยนต์',
      cefrLevel: 'A2',
      phonetic: '/ˈməʊ.tə.saɪ.kəl/',
      exampleSentence: 'He rides a motorcycle to the office.',
      category: 'Vehicles',
    ),
    ScannedVocabulary(
      mlLabel: 'Airplane',
      englishWord: 'airplane',
      thaiTranslation: 'เครื่องบิน',
      cefrLevel: 'A2',
      phonetic: '/ˈeər.pleɪn/',
      exampleSentence: 'The airplane is flying above the clouds.',
      category: 'Vehicles',
    ),
    ScannedVocabulary(
      mlLabel: 'Boat',
      englishWord: 'boat',
      thaiTranslation: 'เรือ',
      cefrLevel: 'A1',
      phonetic: '/bəʊt/',
      exampleSentence: 'We took a boat to the island.',
      category: 'Vehicles',
    ),
    ScannedVocabulary(
      mlLabel: 'Train',
      englishWord: 'train',
      thaiTranslation: 'รถไฟ',
      cefrLevel: 'A1',
      phonetic: '/treɪn/',
      exampleSentence: 'The train departs at noon.',
      category: 'Vehicles',
    ),
    ScannedVocabulary(
      mlLabel: 'Truck',
      englishWord: 'truck',
      thaiTranslation: 'รถบรรทุก',
      cefrLevel: 'A2',
      phonetic: '/trʌk/',
      exampleSentence: 'The truck delivered the goods.',
      category: 'Vehicles',
    ),
    ScannedVocabulary(
      mlLabel: 'Taxi',
      englishWord: 'taxi',
      thaiTranslation: 'แท็กซี่',
      cefrLevel: 'A1',
      phonetic: '/ˈtæk.si/',
      exampleSentence: 'We took a taxi to the airport.',
      category: 'Vehicles',
    ),
    ScannedVocabulary(
      mlLabel: 'Helicopter',
      englishWord: 'helicopter',
      thaiTranslation: 'เฮลิคอปเตอร์',
      cefrLevel: 'B1',
      phonetic: '/ˈhel.ɪ.kɒp.tər/',
      exampleSentence: 'The helicopter landed on the rooftop.',
      category: 'Vehicles',
    ),
    ScannedVocabulary(
      mlLabel: 'Scooter',
      englishWord: 'scooter',
      thaiTranslation: 'สกู๊ตเตอร์',
      cefrLevel: 'A2',
      phonetic: '/ˈskuː.tər/',
      exampleSentence: 'She rides a scooter around the city.',
      category: 'Vehicles',
    ),

    // ── Nature & Plants (ธรรมชาติและพืช) ──
    ScannedVocabulary(
      mlLabel: 'Flower',
      englishWord: 'flower',
      thaiTranslation: 'ดอกไม้',
      cefrLevel: 'A1',
      phonetic: '/ˈflaʊ.ər/',
      exampleSentence: 'The flowers in the garden are beautiful.',
      category: 'Nature',
    ),
    ScannedVocabulary(
      mlLabel: 'Tree',
      englishWord: 'tree',
      thaiTranslation: 'ต้นไม้',
      cefrLevel: 'A1',
      phonetic: '/triː/',
      exampleSentence: 'The tree provides shade in summer.',
      category: 'Nature',
    ),
    ScannedVocabulary(
      mlLabel: 'Leaf',
      englishWord: 'leaf',
      thaiTranslation: 'ใบไม้',
      cefrLevel: 'A2',
      phonetic: '/liːf/',
      exampleSentence: 'The leaves turn red in autumn.',
      category: 'Nature',
    ),
    ScannedVocabulary(
      mlLabel: 'Grass',
      englishWord: 'grass',
      thaiTranslation: 'หญ้า',
      cefrLevel: 'A2',
      phonetic: '/ɡrɑːs/',
      exampleSentence: 'The children played on the grass.',
      category: 'Nature',
    ),
    ScannedVocabulary(
      mlLabel: 'Rock',
      englishWord: 'rock',
      thaiTranslation: 'หิน',
      cefrLevel: 'A2',
      phonetic: '/rɒk/',
      exampleSentence: 'Be careful not to trip on the rock.',
      category: 'Nature',
    ),
    ScannedVocabulary(
      mlLabel: 'Cloud',
      englishWord: 'cloud',
      thaiTranslation: 'เมฆ',
      cefrLevel: 'A2',
      phonetic: '/klaʊd/',
      exampleSentence: 'Dark clouds mean rain is coming.',
      category: 'Nature',
    ),
    ScannedVocabulary(
      mlLabel: 'Sun',
      englishWord: 'sun',
      thaiTranslation: 'ดวงอาทิตย์',
      cefrLevel: 'A1',
      phonetic: '/sʌn/',
      exampleSentence: 'The sun rises in the east.',
      category: 'Nature',
    ),
    ScannedVocabulary(
      mlLabel: 'Moon',
      englishWord: 'moon',
      thaiTranslation: 'ดวงจันทร์',
      cefrLevel: 'A1',
      phonetic: '/muːn/',
      exampleSentence: 'The moon is very bright tonight.',
      category: 'Nature',
    ),
    ScannedVocabulary(
      mlLabel: 'Star',
      englishWord: 'star',
      thaiTranslation: 'ดาว',
      cefrLevel: 'A1',
      phonetic: '/stɑːr/',
      exampleSentence: 'We can see many stars in the sky.',
      category: 'Nature',
    ),
    ScannedVocabulary(
      mlLabel: 'Mountain',
      englishWord: 'mountain',
      thaiTranslation: 'ภูเขา',
      cefrLevel: 'A2',
      phonetic: '/ˈmaʊn.tɪn/',
      exampleSentence: 'We hiked to the top of the mountain.',
      category: 'Nature',
    ),
    ScannedVocabulary(
      mlLabel: 'River',
      englishWord: 'river',
      thaiTranslation: 'แม่น้ำ',
      cefrLevel: 'A2',
      phonetic: '/ˈrɪv.ər/',
      exampleSentence: 'The river flows through the city.',
      category: 'Nature',
    ),

    // ── Personal Items (ของใช้ส่วนตัว) ──
    ScannedVocabulary(
      mlLabel: 'Key',
      englishWord: 'key',
      thaiTranslation: 'กุญแจ',
      cefrLevel: 'A1',
      phonetic: '/kiː/',
      exampleSentence: 'I lost my house key.',
      category: 'Personal Items',
    ),
    ScannedVocabulary(
      mlLabel: 'Wallet',
      englishWord: 'wallet',
      thaiTranslation: 'กระเป๋าสตางค์',
      cefrLevel: 'A2',
      phonetic: '/ˈwɒl.ɪt/',
      exampleSentence: 'My wallet is in my back pocket.',
      category: 'Personal Items',
    ),
    ScannedVocabulary(
      mlLabel: 'Umbrella',
      englishWord: 'umbrella',
      thaiTranslation: 'ร่ม',
      cefrLevel: 'A2',
      phonetic: '/ʌmˈbrel.ə/',
      exampleSentence: 'Bring an umbrella because it might rain.',
      category: 'Personal Items',
    ),
    ScannedVocabulary(
      mlLabel: 'Toothbrush',
      englishWord: 'toothbrush',
      thaiTranslation: 'แปรงสีฟัน',
      cefrLevel: 'A2',
      phonetic: '/ˈtuːθ.brʌʃ/',
      exampleSentence: 'I brush my teeth with a toothbrush.',
      category: 'Personal Items',
    ),
    ScannedVocabulary(
      mlLabel: 'Comb',
      englishWord: 'comb',
      thaiTranslation: 'หวี',
      cefrLevel: 'A2',
      phonetic: '/kəʊm/',
      exampleSentence: 'She used a comb to style her hair.',
      category: 'Personal Items',
    ),
    ScannedVocabulary(
      mlLabel: 'Towel',
      englishWord: 'towel',
      thaiTranslation: 'ผ้าขนหนู',
      cefrLevel: 'A2',
      phonetic: '/taʊəl/',
      exampleSentence: 'Dry your hands with the towel.',
      category: 'Personal Items',
    ),
    ScannedVocabulary(
      mlLabel: 'Soap',
      englishWord: 'soap',
      thaiTranslation: 'สบู่',
      cefrLevel: 'A2',
      phonetic: '/səʊp/',
      exampleSentence: 'Wash your hands with soap and water.',
      category: 'Personal Items',
    ),
    ScannedVocabulary(
      mlLabel: 'Bottle',
      englishWord: 'bottle',
      thaiTranslation: 'ขวด',
      cefrLevel: 'A1',
      phonetic: '/ˈbɒt.əl/',
      exampleSentence: 'Please pass me the water bottle.',
      category: 'Personal Items',
    ),
    ScannedVocabulary(
      mlLabel: 'Bag',
      englishWord: 'bag',
      thaiTranslation: 'กระเป๋า',
      cefrLevel: 'A1',
      phonetic: '/bæɡ/',
      exampleSentence: 'She put her lunch in the bag.',
      category: 'Personal Items',
    ),
    ScannedVocabulary(
      mlLabel: 'Ring',
      englishWord: 'ring',
      thaiTranslation: 'แหวน',
      cefrLevel: 'A2',
      phonetic: '/rɪŋ/',
      exampleSentence: 'She wears a gold ring on her finger.',
      category: 'Personal Items',
    ),
    ScannedVocabulary(
      mlLabel: 'Necklace',
      englishWord: 'necklace',
      thaiTranslation: 'สร้อยคอ',
      cefrLevel: 'B1',
      phonetic: '/ˈnek.ləs/',
      exampleSentence: 'She received a pearl necklace as a gift.',
      category: 'Personal Items',
    ),
    ScannedVocabulary(
      mlLabel: 'Perfume',
      englishWord: 'perfume',
      thaiTranslation: 'น้ำหอม',
      cefrLevel: 'B1',
      phonetic: '/ˈpɜː.fjuːm/',
      exampleSentence: 'This perfume smells like roses.',
      category: 'Personal Items',
    ),

    // ── Sports & Recreation (กีฬาและนันทนาการ) ──
    ScannedVocabulary(
      mlLabel: 'Ball',
      englishWord: 'ball',
      thaiTranslation: 'ลูกบอล',
      cefrLevel: 'A1',
      phonetic: '/bɔːl/',
      exampleSentence: 'Kick the ball into the goal.',
      category: 'Sports',
    ),
    ScannedVocabulary(
      mlLabel: 'Tennis racket',
      englishWord: 'tennis racket',
      thaiTranslation: 'ไม้เทนนิส',
      cefrLevel: 'B1',
      phonetic: '/ˈten.ɪs ˈræk.ɪt/',
      exampleSentence: 'He bought a new tennis racket.',
      category: 'Sports',
    ),
    ScannedVocabulary(
      mlLabel: 'Swimming pool',
      englishWord: 'swimming pool',
      thaiTranslation: 'สระว่ายน้ำ',
      cefrLevel: 'A2',
      phonetic: '/ˈswɪm.ɪŋ puːl/',
      exampleSentence: 'The hotel has a swimming pool.',
      category: 'Sports',
    ),
    ScannedVocabulary(
      mlLabel: 'Skateboard',
      englishWord: 'skateboard',
      thaiTranslation: 'สเก็ตบอร์ด',
      cefrLevel: 'B1',
      phonetic: '/ˈskeɪt.bɔːd/',
      exampleSentence: 'He learned to ride a skateboard.',
      category: 'Sports',
    ),
    ScannedVocabulary(
      mlLabel: 'Helmet',
      englishWord: 'helmet',
      thaiTranslation: 'หมวกกันน็อค',
      cefrLevel: 'A2',
      phonetic: '/ˈhel.mɪt/',
      exampleSentence: 'Always wear a helmet when cycling.',
      category: 'Sports',
    ),
    ScannedVocabulary(
      mlLabel: 'Guitar',
      englishWord: 'guitar',
      thaiTranslation: 'กีตาร์',
      cefrLevel: 'A2',
      phonetic: '/ɡɪˈtɑːr/',
      exampleSentence: 'She plays the guitar beautifully.',
      category: 'Sports',
    ),
    ScannedVocabulary(
      mlLabel: 'Piano',
      englishWord: 'piano',
      thaiTranslation: 'เปียโน',
      cefrLevel: 'A2',
      phonetic: '/piˈæn.əʊ/',
      exampleSentence: 'He practices the piano every evening.',
      category: 'Sports',
    ),

    // ── Kitchen & Household (ห้องครัวและของใช้ในบ้าน) ──
    ScannedVocabulary(
      mlLabel: 'Cup',
      englishWord: 'cup',
      thaiTranslation: 'ถ้วย',
      cefrLevel: 'A1',
      phonetic: '/kʌp/',
      exampleSentence: 'Would you like a cup of coffee?',
      category: 'Kitchen',
    ),
    ScannedVocabulary(
      mlLabel: 'Plate',
      englishWord: 'plate',
      thaiTranslation: 'จาน',
      cefrLevel: 'A1',
      phonetic: '/pleɪt/',
      exampleSentence: 'Put the food on the plate.',
      category: 'Kitchen',
    ),
    ScannedVocabulary(
      mlLabel: 'Bowl',
      englishWord: 'bowl',
      thaiTranslation: 'ชาม',
      cefrLevel: 'A1',
      phonetic: '/bəʊl/',
      exampleSentence: 'She poured soup into the bowl.',
      category: 'Kitchen',
    ),
    ScannedVocabulary(
      mlLabel: 'Fork',
      englishWord: 'fork',
      thaiTranslation: 'ส้อม',
      cefrLevel: 'A1',
      phonetic: '/fɔːk/',
      exampleSentence: 'Use a fork to eat the salad.',
      category: 'Kitchen',
    ),
    ScannedVocabulary(
      mlLabel: 'Spoon',
      englishWord: 'spoon',
      thaiTranslation: 'ช้อน',
      cefrLevel: 'A1',
      phonetic: '/spuːn/',
      exampleSentence: 'Stir the soup with a spoon.',
      category: 'Kitchen',
    ),
    ScannedVocabulary(
      mlLabel: 'Knife',
      englishWord: 'knife',
      thaiTranslation: 'มีด',
      cefrLevel: 'A1',
      phonetic: '/naɪf/',
      exampleSentence: 'Be careful with the sharp knife.',
      category: 'Kitchen',
    ),
    ScannedVocabulary(
      mlLabel: 'Frying pan',
      englishWord: 'frying pan',
      thaiTranslation: 'กระทะ',
      cefrLevel: 'B1',
      phonetic: '/ˈfraɪ.ɪŋ pæn/',
      exampleSentence: 'Heat the oil in the frying pan.',
      category: 'Kitchen',
    ),
    ScannedVocabulary(
      mlLabel: 'Kettle',
      englishWord: 'kettle',
      thaiTranslation: 'กาต้มน้ำ',
      cefrLevel: 'B1',
      phonetic: '/ˈket.əl/',
      exampleSentence: 'Put the kettle on for tea.',
      category: 'Kitchen',
    ),
    ScannedVocabulary(
      mlLabel: 'Refrigerator',
      englishWord: 'refrigerator',
      thaiTranslation: 'ตู้เย็น',
      cefrLevel: 'B1',
      phonetic: '/rɪˈfrɪdʒ.ər.eɪ.tər/',
      exampleSentence: 'Keep the milk in the refrigerator.',
      category: 'Kitchen',
    ),
    ScannedVocabulary(
      mlLabel: 'Microwave',
      englishWord: 'microwave',
      thaiTranslation: 'ไมโครเวฟ',
      cefrLevel: 'B1',
      phonetic: '/ˈmaɪ.krə.weɪv/',
      exampleSentence: 'Heat the food in the microwave for two minutes.',
      category: 'Kitchen',
    ),
    ScannedVocabulary(
      mlLabel: 'Oven',
      englishWord: 'oven',
      thaiTranslation: 'เตาอบ',
      cefrLevel: 'B1',
      phonetic: '/ˈʌv.ən/',
      exampleSentence: 'Preheat the oven to 180 degrees.',
      category: 'Kitchen',
    ),
    ScannedVocabulary(
      mlLabel: 'Washing machine',
      englishWord: 'washing machine',
      thaiTranslation: 'เครื่องซักผ้า',
      cefrLevel: 'B1',
      phonetic: '/ˈwɒʃ.ɪŋ məˌʃiːn/',
      exampleSentence: 'Put the dirty clothes in the washing machine.',
      category: 'Kitchen',
    ),
    ScannedVocabulary(
      mlLabel: 'Clock',
      englishWord: 'clock',
      thaiTranslation: 'นาฬิกา',
      cefrLevel: 'A1',
      phonetic: '/klɒk/',
      exampleSentence: 'The clock on the wall says 3 PM.',
      category: 'Kitchen',
    ),
    ScannedVocabulary(
      mlLabel: 'Candle',
      englishWord: 'candle',
      thaiTranslation: 'เทียน',
      cefrLevel: 'A2',
      phonetic: '/ˈkæn.dəl/',
      exampleSentence: 'She lit a candle during the blackout.',
      category: 'Kitchen',
    ),
  ];
}
