import 'package:flutter/material.dart';

/// Immutable Thai-first presentation metadata for stable navigation IDs.
///
/// This authority never translates route IDs, feature IDs, stored data, or
/// learner content. Consumers must use [require] so a missing registered
/// entry fails closed instead of substituting an English fallback.
final class NavigationGlossaryEntry {
  const NavigationGlossaryEntry({
    required this.id,
    required this.fullThaiLabel,
    required this.shortThaiLabel,
    required this.semanticsLabel,
    required this.tooltip,
    required this.icon,
    this.selectedIcon,
  });

  final String id;
  final String fullThaiLabel;
  final String shortThaiLabel;
  final String semanticsLabel;
  final String tooltip;
  final IconData icon;
  final IconData? selectedIcon;
}

/// Canonical navigation/menu presentation entries keyed by stable IDs.
abstract final class NavigationGlossary {
  static const Set<String> mainDestinationIds = <String>{
    'home/vocabulary',
    'home/learn',
    'home/today',
    'home/study-planning',
    'home/mastery',
    'home/weakness',
    'home/achievements',
    'home/profile',
  };

  static const Set<String> drawerDestinationIds = <String>{
    'drawer/rewards/shop',
    'drawer/practice/object-scanner',
    'drawer/practice/shadowing',
    'drawer/learning/ghost-duel',
    'drawer/ai-tutor/chat',
    'drawer/ai-tutor/settings',
    'drawer/export/center',
    'drawer/rewards/quests',
    'drawer/settings',
  };

  static const Set<String> learningModeIds = <String>{
    'home/learn/associative-reading',
    'home/learn/quiz',
    'home/learn/quiz/typed-recall',
    'home/learn/quiz/matching',
    'home/learn/quiz/cloze',
    'home/learn/quiz/definition',
    'home/learn/srs',
    'home/learn/reading/cefr',
    'home/learn/quiz/dictation',
    'home/learn/quiz/sentence-scramble',
    'home/learn/quiz/word-scramble',
    'home/learn/speech/speaking',
    'home/learn/speech/shadowing',
  };

  static const Set<String> todayActionIds = <String>{
    'today-hub-resume-action',
    'today-hub-start-recommendation',
    'today-hub-assessment-action',
    'today-hub-open-review',
    'today-hub-open-history',
  };

  static const Set<String> studyPlanningActionIds = <String>{
    'study-planning/open-catalog',
    'study-planning/open-goals',
    'study-planning/open-learning-preferences',
  };

  static const Set<String> settingsActionIds = <String>{
    'settings/display',
    'theme-system',
    'theme-light',
    'theme-dark',
    'reduced-motion-switch',
    'settings/account',
    'settings/offline-content',
    'settings/research-consent',
    'settings/cloud-status',
    'settings/change-password',
    'settings/logout',
    'erase-local-data',
  };

  static const Set<String> profileAxisIds = <String>{
    'profile/mastery',
    'profile/srs',
    'profile/effort',
    'profile/accuracy',
    'profile/weakness',
    'profile/engagement',
  };

  static const Set<String> hubChildRouteIds = <String>{
    'home/today/review',
    'home/today/history',
    'research/assessment',
    'study-planning/catalog',
    'study-planning/goals',
    'study-planning/learning-preferences',
  };

  static const Map<String, NavigationGlossaryEntry>
  entries = <String, NavigationGlossaryEntry>{
    'home/vocabulary': NavigationGlossaryEntry(
      id: 'home/vocabulary',
      fullThaiLabel: 'คลังคำศัพท์',
      shortThaiLabel: 'คลังคำศัพท์',
      semanticsLabel: 'เปิดคลังคำศัพท์',
      tooltip: 'เปิดคลังคำศัพท์',
      icon: Icons.menu_book_outlined,
      selectedIcon: Icons.menu_book,
    ),
    'home/learn': NavigationGlossaryEntry(
      id: 'home/learn',
      fullThaiLabel: 'การเรียนรู้',
      shortThaiLabel: 'การเรียนรู้',
      semanticsLabel: 'เปิดการเรียนรู้',
      tooltip: 'เปิดกิจกรรมการเรียนรู้',
      icon: Icons.school_outlined,
      selectedIcon: Icons.school,
    ),
    'home/today': NavigationGlossaryEntry(
      id: 'home/today',
      fullThaiLabel: 'วันนี้',
      shortThaiLabel: 'วันนี้',
      semanticsLabel: 'เปิดกิจกรรมวันนี้',
      tooltip: 'เปิดกิจกรรมวันนี้',
      icon: Icons.today_outlined,
      selectedIcon: Icons.today,
    ),
    'home/study-planning': NavigationGlossaryEntry(
      id: 'home/study-planning',
      fullThaiLabel: 'วางแผนการเรียน',
      shortThaiLabel: 'วางแผน',
      semanticsLabel: 'เปิดวางแผนการเรียน',
      tooltip: 'เปิดวางแผนการเรียน',
      icon: Icons.event_note_outlined,
      selectedIcon: Icons.event_note,
    ),
    'home/mastery': NavigationGlossaryEntry(
      id: 'home/mastery',
      fullThaiLabel: 'ความชำนาญ',
      shortThaiLabel: 'ความชำนาญ',
      semanticsLabel: 'เปิดภาพรวมความชำนาญ',
      tooltip: 'เปิดภาพรวมความชำนาญ',
      icon: Icons.analytics_outlined,
      selectedIcon: Icons.analytics,
    ),
    'home/weakness': NavigationGlossaryEntry(
      id: 'home/weakness',
      fullThaiLabel: 'จุดที่ควรฝึกเพิ่ม',
      shortThaiLabel: 'ฝึกเพิ่ม',
      semanticsLabel: 'เปิดจุดที่ควรฝึกเพิ่ม',
      tooltip: 'เปิดจุดที่ควรฝึกเพิ่ม',
      icon: Icons.healing_outlined,
      selectedIcon: Icons.healing,
    ),
    'home/achievements': NavigationGlossaryEntry(
      id: 'home/achievements',
      fullThaiLabel: 'รางวัล',
      shortThaiLabel: 'รางวัล',
      semanticsLabel: 'เปิดรางวัล',
      tooltip: 'เปิดรางวัล',
      icon: Icons.emoji_events_outlined,
      selectedIcon: Icons.emoji_events,
    ),
    'home/profile': NavigationGlossaryEntry(
      id: 'home/profile',
      fullThaiLabel: 'โปรไฟล์',
      shortThaiLabel: 'โปรไฟล์',
      semanticsLabel: 'เปิดโปรไฟล์',
      tooltip: 'เปิดโปรไฟล์',
      icon: Icons.person_outlined,
      selectedIcon: Icons.person,
    ),
    'drawer/rewards/shop': NavigationGlossaryEntry(
      id: 'drawer/rewards/shop',
      fullThaiLabel: 'ร้านค้า',
      shortThaiLabel: 'ร้านค้า',
      semanticsLabel: 'เปิดร้านค้า',
      tooltip: 'เปิดร้านค้า',
      icon: Icons.shopping_bag,
    ),
    'drawer/practice/object-scanner': NavigationGlossaryEntry(
      id: 'drawer/practice/object-scanner',
      fullThaiLabel: 'สแกนวัตถุ',
      shortThaiLabel: 'สแกนวัตถุ',
      semanticsLabel: 'เปิดสแกนวัตถุ',
      tooltip: 'เปิดสแกนวัตถุ',
      icon: Icons.document_scanner_outlined,
    ),
    'drawer/practice/shadowing': NavigationGlossaryEntry(
      id: 'drawer/practice/shadowing',
      fullThaiLabel: 'ฝึกพูดตามเสียง',
      shortThaiLabel: 'ฝึกพูดตามเสียง',
      semanticsLabel: 'เปิดฝึกพูดตามเสียง',
      tooltip: 'เปิดฝึกพูดตามเสียง',
      icon: Icons.mic_none,
    ),
    'drawer/learning/ghost-duel': NavigationGlossaryEntry(
      id: 'drawer/learning/ghost-duel',
      fullThaiLabel: 'ดวลกับสถิติเดิม',
      shortThaiLabel: 'ดวลกับสถิติเดิม',
      semanticsLabel: 'เปิดดวลกับสถิติเดิม',
      tooltip: 'เปิดกิจกรรมเปรียบเทียบกับสถิติเดิม',
      icon: Icons.sports_esports_outlined,
    ),
    'drawer/ai-tutor/chat': NavigationGlossaryEntry(
      id: 'drawer/ai-tutor/chat',
      fullThaiLabel: 'ผู้ช่วยสอน AI',
      shortThaiLabel: 'ผู้ช่วยสอน AI',
      semanticsLabel: 'เปิดผู้ช่วยสอน AI',
      tooltip: 'เปิดผู้ช่วยสอน AI',
      icon: Icons.chat_bubble_outline,
    ),
    'drawer/ai-tutor/settings': NavigationGlossaryEntry(
      id: 'drawer/ai-tutor/settings',
      fullThaiLabel: 'ตั้งค่าการเชื่อมต่อ AI',
      shortThaiLabel: 'ตั้งค่า AI',
      semanticsLabel: 'เปิดตั้งค่าการเชื่อมต่อ AI',
      tooltip: 'จัดการกุญแจส่วนตัวที่เก็บในเครื่อง',
      icon: Icons.key_outlined,
    ),
    'drawer/export/center': NavigationGlossaryEntry(
      id: 'drawer/export/center',
      fullThaiLabel: 'ส่งออกข้อมูล',
      shortThaiLabel: 'ส่งออกข้อมูล',
      semanticsLabel: 'เปิดการส่งออกข้อมูล',
      tooltip: 'เปิดการส่งออกข้อมูล',
      icon: Icons.file_download_outlined,
    ),
    'drawer/rewards/quests': NavigationGlossaryEntry(
      id: 'drawer/rewards/quests',
      fullThaiLabel: 'ภารกิจการเรียน',
      shortThaiLabel: 'ภารกิจ',
      semanticsLabel: 'เปิดภารกิจการเรียน',
      tooltip: 'เปิดภารกิจการเรียน',
      icon: Icons.flag_outlined,
    ),
    'drawer/settings': NavigationGlossaryEntry(
      id: 'drawer/settings',
      fullThaiLabel: 'ตั้งค่า',
      shortThaiLabel: 'ตั้งค่า',
      semanticsLabel: 'เปิดการตั้งค่า',
      tooltip: 'เปิดการตั้งค่า',
      icon: Icons.settings,
    ),
    'home/learn/associative-reading': NavigationGlossaryEntry(
      id: 'home/learn/associative-reading',
      fullThaiLabel: 'อ่านเชื่อมโยงความจำ',
      shortThaiLabel: 'อ่านเชื่อมโยงความจำ',
      semanticsLabel: 'เปิดอ่านเชื่อมโยงความจำ',
      tooltip: 'สร้างเรื่องเชื่อมโยงคำศัพท์เพื่อช่วยจำ',
      icon: Icons.auto_stories_outlined,
    ),
    'home/learn/quiz': NavigationGlossaryEntry(
      id: 'home/learn/quiz',
      fullThaiLabel: 'แบบทดสอบจากคลังคำศัพท์',
      shortThaiLabel: 'แบบทดสอบ',
      semanticsLabel: 'เปิดแบบทดสอบจากคลังคำศัพท์',
      tooltip: 'ตอบความหมายจากคำศัพท์ที่บันทึกไว้',
      icon: Icons.quiz_outlined,
    ),
    'home/learn/quiz/typed-recall': NavigationGlossaryEntry(
      id: 'home/learn/quiz/typed-recall',
      fullThaiLabel: 'นึกคำแล้วพิมพ์',
      shortThaiLabel: 'นึกคำแล้วพิมพ์',
      semanticsLabel: 'เปิดกิจกรรมนึกคำแล้วพิมพ์',
      tooltip: 'นึกตัวสะกดจากความจำแล้วพิมพ์คำตอบ',
      icon: Icons.keyboard_outlined,
    ),
    'home/learn/quiz/matching': NavigationGlossaryEntry(
      id: 'home/learn/quiz/matching',
      fullThaiLabel: 'จับคู่คำศัพท์',
      shortThaiLabel: 'จับคู่คำศัพท์',
      semanticsLabel: 'เปิดกิจกรรมจับคู่คำศัพท์',
      tooltip: 'จับคู่คำศัพท์กับความหมาย',
      icon: Icons.compare_arrows_outlined,
    ),
    'home/learn/quiz/cloze': NavigationGlossaryEntry(
      id: 'home/learn/quiz/cloze',
      fullThaiLabel: 'เติมคำในประโยค',
      shortThaiLabel: 'เติมคำในประโยค',
      semanticsLabel: 'เปิดกิจกรรมเติมคำในประโยค',
      tooltip: 'เลือกหรือพิมพ์คำลงในประโยคที่ตรวจทานแล้ว',
      icon: Icons.space_bar_outlined,
    ),
    'home/learn/quiz/definition': NavigationGlossaryEntry(
      id: 'home/learn/quiz/definition',
      fullThaiLabel: 'เลือกคำจากคำอธิบาย',
      shortThaiLabel: 'เลือกคำจากคำอธิบาย',
      semanticsLabel: 'เปิดกิจกรรมเลือกคำจากคำอธิบาย',
      tooltip: 'เลือกคำศัพท์จากคำอธิบายที่ตรวจทานแล้ว',
      icon: Icons.menu_book_outlined,
    ),
    'home/learn/srs': NavigationGlossaryEntry(
      id: 'home/learn/srs',
      fullThaiLabel: 'ทบทวนแบบเว้นระยะ (SRS)',
      shortThaiLabel: 'ทบทวน (SRS)',
      semanticsLabel: 'เปิดทบทวนแบบเว้นระยะ SRS',
      tooltip: 'ทบทวนคำศัพท์ตามกำหนดจากประวัติคำตอบ',
      icon: Icons.event_repeat_outlined,
    ),
    'home/learn/reading/cefr': NavigationGlossaryEntry(
      id: 'home/learn/reading/cefr',
      fullThaiLabel: 'อ่านตามระดับภาษา CEFR',
      shortThaiLabel: 'อ่าน CEFR',
      semanticsLabel: 'เปิดอ่านตามระดับภาษา CEFR',
      tooltip: 'อ่านบทความตามระดับภาษา CEFR',
      icon: Icons.chrome_reader_mode_outlined,
    ),
    'home/learn/quiz/dictation': NavigationGlossaryEntry(
      id: 'home/learn/quiz/dictation',
      fullThaiLabel: 'ฟังแล้วพิมพ์',
      shortThaiLabel: 'ฟังแล้วพิมพ์',
      semanticsLabel: 'เปิดกิจกรรมฟังแล้วพิมพ์',
      tooltip: 'ฟังเสียงแล้วพิมพ์คำศัพท์',
      icon: Icons.hearing_outlined,
    ),
    'home/learn/quiz/sentence-scramble': NavigationGlossaryEntry(
      id: 'home/learn/quiz/sentence-scramble',
      fullThaiLabel: 'เรียงประโยค',
      shortThaiLabel: 'เรียงประโยค',
      semanticsLabel: 'เปิดกิจกรรมเรียงประโยค',
      tooltip: 'เรียงคำให้เป็นประโยคที่ถูกต้อง',
      icon: Icons.format_list_numbered_outlined,
    ),
    'home/learn/quiz/word-scramble': NavigationGlossaryEntry(
      id: 'home/learn/quiz/word-scramble',
      fullThaiLabel: 'เรียงตัวอักษร',
      shortThaiLabel: 'เรียงตัวอักษร',
      semanticsLabel: 'เปิดกิจกรรมเรียงตัวอักษร',
      tooltip: 'เรียงตัวอักษรให้เป็นคำศัพท์',
      icon: Icons.extension_outlined,
    ),
    'home/learn/speech/speaking': NavigationGlossaryEntry(
      id: 'home/learn/speech/speaking',
      fullThaiLabel: 'ฝึกออกเสียง',
      shortThaiLabel: 'ฝึกออกเสียง',
      semanticsLabel: 'เปิดกิจกรรมฝึกออกเสียง',
      tooltip: 'ฝึกออกเสียงด้วยการรู้จำเสียงบนอุปกรณ์',
      icon: Icons.mic_outlined,
    ),
    'home/learn/speech/shadowing': NavigationGlossaryEntry(
      id: 'home/learn/speech/shadowing',
      fullThaiLabel: 'ฝึกพูดตามเสียง',
      shortThaiLabel: 'ฝึกพูดตามเสียง',
      semanticsLabel: 'เปิดกิจกรรมฝึกพูดตามเสียง',
      tooltip: 'ฟังตัวอย่างแล้วฝึกพูดตาม',
      icon: Icons.record_voice_over_outlined,
    ),
    'today-hub-resume-action': NavigationGlossaryEntry(
      id: 'today-hub-resume-action',
      fullThaiLabel: 'เรียนต่อ',
      shortThaiLabel: 'เรียนต่อ',
      semanticsLabel: 'เรียนต่อจากกิจกรรมเดิม',
      tooltip: 'เรียนต่อจากกิจกรรมเดิม',
      icon: Icons.play_arrow,
    ),
    'today-hub-start-recommendation': NavigationGlossaryEntry(
      id: 'today-hub-start-recommendation',
      fullThaiLabel: 'เริ่มกิจกรรมที่แนะนำ',
      shortThaiLabel: 'เริ่มกิจกรรมที่แนะนำ',
      semanticsLabel: 'เริ่มกิจกรรมที่แนะนำ',
      tooltip: 'เริ่มกิจกรรมที่แนะนำสำหรับวันนี้',
      icon: Icons.auto_awesome_outlined,
    ),
    'today-hub-assessment-action': NavigationGlossaryEntry(
      id: 'today-hub-assessment-action',
      fullThaiLabel: 'เริ่มแบบประเมิน',
      shortThaiLabel: 'เริ่มแบบประเมิน',
      semanticsLabel: 'เริ่มแบบประเมินที่ได้รับมอบหมาย',
      tooltip: 'เริ่มแบบประเมินที่ได้รับมอบหมาย',
      icon: Icons.assignment_outlined,
    ),
    'today-hub-open-review': NavigationGlossaryEntry(
      id: 'today-hub-open-review',
      fullThaiLabel: 'เปิดศูนย์ทบทวน',
      shortThaiLabel: 'เปิดศูนย์ทบทวน',
      semanticsLabel: 'เปิดศูนย์ทบทวน',
      tooltip: 'เปิดศูนย์ทบทวน',
      icon: Icons.fact_check_outlined,
    ),
    'today-hub-open-history': NavigationGlossaryEntry(
      id: 'today-hub-open-history',
      fullThaiLabel: 'ดูประวัติการเรียน',
      shortThaiLabel: 'ดูประวัติการเรียน',
      semanticsLabel: 'เปิดประวัติการเรียน',
      tooltip: 'เปิดประวัติการเรียน',
      icon: Icons.history,
    ),
    'study-planning/open-catalog': NavigationGlossaryEntry(
      id: 'study-planning/open-catalog',
      fullThaiLabel: 'เลือกชุดเนื้อหาการเรียน',
      shortThaiLabel: 'เลือกชุดเนื้อหา',
      semanticsLabel: 'เปิดชุดเนื้อหาการเรียนที่ตรวจสอบแล้ว',
      tooltip: 'เปิดชุดเนื้อหาการเรียนที่ตรวจสอบแล้ว',
      icon: Icons.menu_book_outlined,
    ),
    'study-planning/open-goals': NavigationGlossaryEntry(
      id: 'study-planning/open-goals',
      fullThaiLabel: 'เป้าหมายการเรียน',
      shortThaiLabel: 'เป้าหมายการเรียน',
      semanticsLabel: 'เปิดเป้าหมายการเรียน',
      tooltip: 'เปิดเป้าหมายการเรียน',
      icon: Icons.flag_outlined,
    ),
    'study-planning/open-learning-preferences': NavigationGlossaryEntry(
      id: 'study-planning/open-learning-preferences',
      fullThaiLabel: 'การตั้งค่าการเรียน',
      shortThaiLabel: 'การตั้งค่าการเรียน',
      semanticsLabel: 'เปิดการตั้งค่าการเรียน',
      tooltip: 'เปิดการตั้งค่าการเรียน',
      icon: Icons.tune_outlined,
    ),
    'settings/display': NavigationGlossaryEntry(
      id: 'settings/display',
      fullThaiLabel: 'การแสดงผล',
      shortThaiLabel: 'การแสดงผล',
      semanticsLabel: 'การตั้งค่าการแสดงผล',
      tooltip: 'การตั้งค่าการแสดงผล',
      icon: Icons.display_settings_outlined,
    ),
    'theme-system': NavigationGlossaryEntry(
      id: 'theme-system',
      fullThaiLabel: 'ระบบ',
      shortThaiLabel: 'ระบบ',
      semanticsLabel: 'ใช้รูปแบบตามระบบ',
      tooltip: 'ใช้รูปแบบตามระบบ',
      icon: Icons.settings_suggest_outlined,
    ),
    'theme-light': NavigationGlossaryEntry(
      id: 'theme-light',
      fullThaiLabel: 'สว่าง',
      shortThaiLabel: 'สว่าง',
      semanticsLabel: 'ใช้รูปแบบสว่าง',
      tooltip: 'ใช้รูปแบบสว่าง',
      icon: Icons.light_mode_outlined,
    ),
    'theme-dark': NavigationGlossaryEntry(
      id: 'theme-dark',
      fullThaiLabel: 'มืด',
      shortThaiLabel: 'มืด',
      semanticsLabel: 'ใช้รูปแบบมืด',
      tooltip: 'ใช้รูปแบบมืด',
      icon: Icons.dark_mode_outlined,
    ),
    'reduced-motion-switch': NavigationGlossaryEntry(
      id: 'reduced-motion-switch',
      fullThaiLabel: 'ลดการเคลื่อนไหว',
      shortThaiLabel: 'ลดการเคลื่อนไหว',
      semanticsLabel: 'เปิดหรือปิดการลดการเคลื่อนไหว',
      tooltip: 'เปิดหรือปิดการลดการเคลื่อนไหว',
      icon: Icons.motion_photos_off_outlined,
    ),
    'settings/account': NavigationGlossaryEntry(
      id: 'settings/account',
      fullThaiLabel: 'บัญชีผู้ใช้',
      shortThaiLabel: 'บัญชีผู้ใช้',
      semanticsLabel: 'ข้อมูลบัญชีผู้ใช้',
      tooltip: 'ข้อมูลบัญชีผู้ใช้',
      icon: Icons.person_outline,
    ),
    'settings/offline-content': NavigationGlossaryEntry(
      id: 'settings/offline-content',
      fullThaiLabel: 'เนื้อหาออฟไลน์',
      shortThaiLabel: 'เนื้อหาออฟไลน์',
      semanticsLabel: 'เปิดการจัดการเนื้อหาออฟไลน์',
      tooltip: 'เปิดการจัดการเนื้อหาออฟไลน์',
      icon: Icons.offline_pin_outlined,
    ),
    'settings/research-consent': NavigationGlossaryEntry(
      id: 'settings/research-consent',
      fullThaiLabel: 'ความยินยอมงานวิจัย',
      shortThaiLabel: 'ความยินยอมงานวิจัย',
      semanticsLabel: 'จัดการความยินยอมงานวิจัย',
      tooltip: 'จัดการความยินยอมงานวิจัย',
      icon: Icons.fact_check_outlined,
    ),
    'settings/cloud-status': NavigationGlossaryEntry(
      id: 'settings/cloud-status',
      fullThaiLabel: 'สถานะการเชื่อมต่อระบบออนไลน์',
      shortThaiLabel: 'สถานะออนไลน์',
      semanticsLabel: 'ตรวจสอบสถานะการเชื่อมต่อระบบออนไลน์',
      tooltip: 'ตรวจสอบสถานะการเชื่อมต่อระบบออนไลน์',
      icon: Icons.cloud_done_outlined,
    ),
    'settings/change-password': NavigationGlossaryEntry(
      id: 'settings/change-password',
      fullThaiLabel: 'เปลี่ยนรหัสผ่าน',
      shortThaiLabel: 'เปลี่ยนรหัสผ่าน',
      semanticsLabel: 'เปิดการเปลี่ยนรหัสผ่าน',
      tooltip: 'เปิดการเปลี่ยนรหัสผ่าน',
      icon: Icons.password_outlined,
    ),
    'settings/logout': NavigationGlossaryEntry(
      id: 'settings/logout',
      fullThaiLabel: 'ออกจากระบบ',
      shortThaiLabel: 'ออกจากระบบ',
      semanticsLabel: 'ออกจากระบบ',
      tooltip: 'ออกจากระบบ',
      icon: Icons.logout,
    ),
    'erase-local-data': NavigationGlossaryEntry(
      id: 'erase-local-data',
      fullThaiLabel: 'ลบข้อมูลในเครื่องทั้งหมด',
      shortThaiLabel: 'ลบข้อมูลในเครื่องทั้งหมด',
      semanticsLabel: 'ลบข้อมูลในเครื่องทั้งหมด',
      tooltip:
          'ลบคำศัพท์ ประวัติการเรียน ความยินยอม และกุญแจ AI ที่บันทึกในเครื่อง',
      icon: Icons.delete_forever_outlined,
    ),
    'profile/mastery': NavigationGlossaryEntry(
      id: 'profile/mastery',
      fullThaiLabel: 'ความชำนาญ',
      shortThaiLabel: 'ความชำนาญ',
      semanticsLabel: 'ความชำนาญ',
      tooltip: 'ความชำนาญ',
      icon: Icons.analytics_outlined,
    ),
    'profile/srs': NavigationGlossaryEntry(
      id: 'profile/srs',
      fullThaiLabel: 'ทบทวนแบบเว้นระยะ (SRS)',
      shortThaiLabel: 'ทบทวน (SRS)',
      semanticsLabel: 'สถานะการทบทวนแบบเว้นระยะ SRS',
      tooltip: 'สถานะการทบทวนแบบเว้นระยะ SRS',
      icon: Icons.event_repeat_outlined,
    ),
    'profile/effort': NavigationGlossaryEntry(
      id: 'profile/effort',
      fullThaiLabel: 'เวลาเรียนจริง',
      shortThaiLabel: 'เวลาเรียนจริง',
      semanticsLabel: 'เวลาเรียนจริง',
      tooltip: 'เวลาเรียนจริง',
      icon: Icons.timer_outlined,
    ),
    'profile/accuracy': NavigationGlossaryEntry(
      id: 'profile/accuracy',
      fullThaiLabel: 'ความแม่นยำ',
      shortThaiLabel: 'ความแม่นยำ',
      semanticsLabel: 'ความแม่นยำ',
      tooltip: 'ความแม่นยำ',
      icon: Icons.check_circle_outline,
    ),
    'profile/weakness': NavigationGlossaryEntry(
      id: 'profile/weakness',
      fullThaiLabel: 'จุดที่ควรฝึกเพิ่ม',
      shortThaiLabel: 'จุดที่ควรฝึกเพิ่ม',
      semanticsLabel: 'จุดที่ควรฝึกเพิ่ม',
      tooltip: 'จุดที่ควรฝึกเพิ่ม',
      icon: Icons.healing_outlined,
    ),
    'profile/engagement': NavigationGlossaryEntry(
      id: 'profile/engagement',
      fullThaiLabel: 'ความต่อเนื่องในการเรียน',
      shortThaiLabel: 'ความต่อเนื่องในการเรียน',
      semanticsLabel: 'ความต่อเนื่องในการเรียน',
      tooltip: 'ความต่อเนื่องในการเรียน',
      icon: Icons.local_fire_department_outlined,
    ),
    'home/today/review': NavigationGlossaryEntry(
      id: 'home/today/review',
      fullThaiLabel: 'ศูนย์ทบทวน',
      shortThaiLabel: 'ศูนย์ทบทวน',
      semanticsLabel: 'ศูนย์ทบทวน',
      tooltip: 'ศูนย์ทบทวน',
      icon: Icons.fact_check_outlined,
    ),
    'home/today/history': NavigationGlossaryEntry(
      id: 'home/today/history',
      fullThaiLabel: 'ประวัติการเรียน',
      shortThaiLabel: 'ประวัติการเรียน',
      semanticsLabel: 'ประวัติการเรียน',
      tooltip: 'ประวัติการเรียน',
      icon: Icons.history,
    ),
    'research/assessment': NavigationGlossaryEntry(
      id: 'research/assessment',
      fullThaiLabel: 'แบบประเมิน',
      shortThaiLabel: 'แบบประเมิน',
      semanticsLabel: 'แบบประเมินที่ได้รับมอบหมาย',
      tooltip: 'แบบประเมินที่ได้รับมอบหมาย',
      icon: Icons.assignment_outlined,
    ),
    'study-planning/catalog': NavigationGlossaryEntry(
      id: 'study-planning/catalog',
      fullThaiLabel: 'ชุดเนื้อหาการเรียน',
      shortThaiLabel: 'ชุดเนื้อหาการเรียน',
      semanticsLabel: 'ชุดเนื้อหาการเรียน',
      tooltip: 'ชุดเนื้อหาการเรียน',
      icon: Icons.menu_book_outlined,
    ),
    'study-planning/goals': NavigationGlossaryEntry(
      id: 'study-planning/goals',
      fullThaiLabel: 'เป้าหมายการเรียน',
      shortThaiLabel: 'เป้าหมายการเรียน',
      semanticsLabel: 'เป้าหมายการเรียน',
      tooltip: 'เป้าหมายการเรียน',
      icon: Icons.flag_outlined,
    ),
    'study-planning/learning-preferences': NavigationGlossaryEntry(
      id: 'study-planning/learning-preferences',
      fullThaiLabel: 'การตั้งค่าการเรียน',
      shortThaiLabel: 'การตั้งค่าการเรียน',
      semanticsLabel: 'การตั้งค่าการเรียน',
      tooltip: 'การตั้งค่าการเรียน',
      icon: Icons.tune_outlined,
    ),
  };

  static NavigationGlossaryEntry require(String id) {
    final entry = entries[id];
    if (entry == null) {
      throw StateError('Missing navigation glossary entry: $id');
    }
    return entry;
  }
}
