-- Derived from accepted historical 7b8ac6cc learning_database.dart schema1.
CREATE TABLE learning_commits (owner_id TEXT NOT NULL, schema_version INTEGER NOT NULL DEFAULT 1, created_at_utc INTEGER NOT NULL, updated_at_utc INTEGER NOT NULL, commit_id TEXT NOT NULL, recorded_at_utc INTEGER NOT NULL, record_count INTEGER NOT NULL, content_fingerprint TEXT NOT NULL, PRIMARY KEY(owner_id, commit_id));
CREATE TABLE associations (owner_id TEXT NOT NULL, schema_version INTEGER NOT NULL DEFAULT 1, created_at_utc INTEGER NOT NULL, updated_at_utc INTEGER NOT NULL, association_id TEXT NOT NULL, word_key TEXT NOT NULL, cue_type TEXT NOT NULL, cue_text TEXT NOT NULL, origin TEXT NOT NULL, strength REAL NOT NULL, success_count INTEGER NOT NULL, failure_count INTEGER NOT NULL, PRIMARY KEY(owner_id, association_id));
CREATE TABLE reading_sessions (owner_id TEXT NOT NULL, schema_version INTEGER NOT NULL DEFAULT 1, created_at_utc INTEGER NOT NULL, updated_at_utc INTEGER NOT NULL, session_id TEXT NOT NULL, cefr_level TEXT NOT NULL, target_word_keys_json TEXT NOT NULL, mix_policy_version TEXT NOT NULL, content_id TEXT NOT NULL, content_version TEXT NOT NULL, current_stage TEXT NOT NULL, started_at_utc INTEGER NOT NULL, completed_at_utc INTEGER, abandoned_at_utc INTEGER, PRIMARY KEY(owner_id, session_id));
CREATE TABLE recall_attempts (owner_id TEXT NOT NULL, schema_version INTEGER NOT NULL DEFAULT 1, created_at_utc INTEGER NOT NULL, updated_at_utc INTEGER NOT NULL, attempt_id TEXT NOT NULL, session_id TEXT NOT NULL, word_key TEXT NOT NULL, recall_mode TEXT NOT NULL, cue_level TEXT NOT NULL, correctness INTEGER NOT NULL, response_time_ms INTEGER NOT NULL, confidence INTEGER NOT NULL, context_id TEXT, algorithm_version TEXT NOT NULL, occurred_at_utc INTEGER NOT NULL, PRIMARY KEY(owner_id, attempt_id));
CREATE TABLE memory_states (owner_id TEXT NOT NULL, schema_version INTEGER NOT NULL DEFAULT 1, created_at_utc INTEGER NOT NULL, updated_at_utc INTEGER NOT NULL, word_key TEXT NOT NULL, strength REAL NOT NULL, cue_dependency REAL NOT NULL, stability REAL NOT NULL, difficulty REAL NOT NULL, lapse_count INTEGER NOT NULL, last_reviewed_at_utc INTEGER, next_due_at_utc INTEGER NOT NULL, last_error_type TEXT, algorithm_version TEXT NOT NULL, PRIMARY KEY(owner_id, word_key));
CREATE TABLE learning_events (owner_id TEXT NOT NULL, schema_version INTEGER NOT NULL DEFAULT 1, created_at_utc INTEGER NOT NULL, updated_at_utc INTEGER NOT NULL, event_id TEXT NOT NULL, occurred_at_utc INTEGER NOT NULL, activity TEXT NOT NULL, content_id TEXT NOT NULL, category_id TEXT, cefr_level TEXT, skill TEXT NOT NULL, correct INTEGER NOT NULL, score INTEGER NOT NULL, response_time_ms INTEGER, attempt_number INTEGER NOT NULL, app_version TEXT NOT NULL, build_id TEXT NOT NULL, PRIMARY KEY(owner_id, event_id));
CREATE TABLE sync_outbox (owner_id TEXT NOT NULL, schema_version INTEGER NOT NULL DEFAULT 1, created_at_utc INTEGER NOT NULL, updated_at_utc INTEGER NOT NULL, outbox_id TEXT NOT NULL, event_id TEXT NOT NULL, operation TEXT NOT NULL, payload_json TEXT NOT NULL, acknowledged_at_utc INTEGER, attempt_count INTEGER NOT NULL, PRIMARY KEY(owner_id, outbox_id));
CREATE TABLE deletion_tombstones (owner_id TEXT NOT NULL, schema_version INTEGER NOT NULL DEFAULT 1, created_at_utc INTEGER NOT NULL, updated_at_utc INTEGER NOT NULL, tombstone_id TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, deleted_at_utc INTEGER NOT NULL, PRIMARY KEY(owner_id, tombstone_id));
PRAGMA user_version=1;
