// Generated by tools/validate_cefr_editorial.py; do not edit.
const cefrEditorialChecksums = <String, String>{
  'assets/content/cefr_editorial/batch-1.json':
      'd7ab58a1cce6d7d30b92418b234161ab1a75088da7934516f33d5791159b027b',
  'assets/content/cefr_editorial/batch-2.json':
      '9a53ab6653d1fcebd61d8cf9a6251e11b5075e26ea865cc819e3fb29d100e46e',
  'assets/content/cefr_editorial/batch-3.json':
      'b2534412e7ee71bb913f229952902f25e5d46265931a094dd6cd1316d3642f06',
  'assets/content/cefr_editorial/complete-1.json':
      'c615817a58afb6ecb9b5c24d8c35b8b5d9f1af133a9ba659697858d8ff953551',
  'assets/content/cefr_editorial/complete-2.json':
      'f173b57c3540c4e44b39fe8ade0be7c6b1c75961ff39d74fbc90a930c3cab0c9',
  'assets/content/cefr_editorial/complete-3.json':
      '3c0d6c460b99f99c99b51371f101dbd668de48c2dc93e8ebde1cd99e24647d3f',
};
const cefrEditorialExpectedCount = 5500;
const cefrSenseReviewChecksums = <String, String>{
  'assets/content/cefr_editorial/sense-review-1.json':
      'c3fcc05d70288e528517a6cbea1881cd285dbb7410fcd43243e80a4c8fa223eb',
  'assets/content/cefr_editorial/sense-review-2.json':
      'ebb94097be4a1d6a47f24849b0a76f2967af70c3f6c662e9d9e321f4d498278a',
  'assets/content/cefr_editorial/sense-review-3.json':
      'a2c9b8f1178fd0e6c5b4370fc46d7fd597cf477812dfbc5b326491ab5e3fd804',
};
