// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with Firebase.initializeApp().
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return android;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl2g3NcdURDucF1W5Jms-90kcrKUbqNt4',
    appId: '1:145034183638:web:719eb38067864496be5a77',
    messagingSenderId: '145034183638',
    projectId: 'vocab-learning-app-219ef',
    authDomain: 'vocab-learning-app-219ef.firebaseapp.com',
    storageBucket: 'vocab-learning-app-219ef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl2g3NcdURDucF1W5Jms-90kcrKUbqNt4',
    appId: '1:145034183638:android:719eb38067864496be5a77',
    messagingSenderId: '145034183638',
    projectId: 'vocab-learning-app-219ef',
    storageBucket: 'vocab-learning-app-219ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl2g3NcdURDucF1W5Jms-90kcrKUbqNt4',
    appId: '1:145034183638:ios:719eb38067864496be5a77',
    messagingSenderId: '145034183638',
    projectId: 'vocab-learning-app-219ef',
    storageBucket: 'vocab-learning-app-219ef.firebasestorage.app',
    iosBundleId: 'com.example.vocabLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl2g3NcdURDucF1W5Jms-90kcrKUbqNt4',
    appId: '1:145034183638:ios:719eb38067864496be5a77',
    messagingSenderId: '145034183638',
    projectId: 'vocab-learning-app-219ef',
    storageBucket: 'vocab-learning-app-219ef.firebasestorage.app',
    iosBundleId: 'com.example.vocabLearningApp',
  );
}
